// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_YcpZDEbI4usaPQmQZBnEvuf_k_Xr8Y',
    appId: '1:30074248936:web:f62e83a2aaf7cbe16d735d',
    messagingSenderId: '30074248936',
    projectId: 'tarea-7a6bc',
    authDomain: 'tarea-7a6bc.firebaseapp.com',
    storageBucket: 'tarea-7a6bc.appspot.com',
    measurementId: 'G-7M6Y10CRTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-kAq3fag1QGsw6b9iXTA_KhZom9stLHw',
    appId: '1:30074248936:android:07ac2d00151a25ee6d735d',
    messagingSenderId: '30074248936',
    projectId: 'tarea-7a6bc',
    storageBucket: 'tarea-7a6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVEiWlPlvtmhSbnPd9TfDTC8soQv8JaY',
    appId: '1:30074248936:ios:6c5fc8321ba10e906d735d',
    messagingSenderId: '30074248936',
    projectId: 'tarea-7a6bc',
    storageBucket: 'tarea-7a6bc.appspot.com',
    iosBundleId: 'com.example.tareas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVEiWlPlvtmhSbnPd9TfDTC8soQv8JaY',
    appId: '1:30074248936:ios:6c5fc8321ba10e906d735d',
    messagingSenderId: '30074248936',
    projectId: 'tarea-7a6bc',
    storageBucket: 'tarea-7a6bc.appspot.com',
    iosBundleId: 'com.example.tareas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_YcpZDEbI4usaPQmQZBnEvuf_k_Xr8Y',
    appId: '1:30074248936:web:80deb4bbf7f58bd76d735d',
    messagingSenderId: '30074248936',
    projectId: 'tarea-7a6bc',
    authDomain: 'tarea-7a6bc.firebaseapp.com',
    storageBucket: 'tarea-7a6bc.appspot.com',
    measurementId: 'G-7GCS8F2E67',
  );
}
